spring:
  datasource:
    url: jdbc:postgresql://192.168.2.3:5432/hotel
    username: hotel_checker
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    filters: stat,wall
    max-active: 12