spring:
  datasource:
    url: jdbc:postgresql://10.16.136.92:5432/hotel
    username: hotel_checker
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:
        enabled: true
      filters: stat,wall
      filter:
        wall:
          enabled: true
        stat:
          enabled: true
      aop-patterns: com.sustech.ooad.*

mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

server:
  port: 8080